# Usar la imagen base oficial de .NET
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Usar la imagen base de build de .NET
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["MicroservicioCuenta.Api/MicroservicioCuenta.Api.csproj", "MicroservicioCuenta.Api/"]
RUN dotnet restore "MicroservicioCuenta.Api/MicroservicioCuenta.Api.csproj"
COPY . .
WORKDIR "/src/MicroservicioCuenta.Api"
RUN dotnet build "MicroservicioCuenta.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MicroservicioCuenta.Api.csproj" -c Release -o /app/publish

# Crear la imagen final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MicroservicioCuenta.Api.dll"]
